############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Acerca"
url = "acerca/"
weight = 2

[[main]]
name = "Contacto"
url = "contacto/"
weight = 3

[[main]]
name = "Páginas"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Páginas"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Páginas"
  name = "Categories"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Inicio"
url = "/"
weight = 1

[[footer]]
name = "Acerca"
url = "acerca/"
weight = 2

[[footer]]
name = "Contacto"
url = "contacto/"
weight = 3

[[footer]]
name = "Política de Privacidad"
url = "politica-privacidad/"
weight = 4
