#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Bisstox"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Bisstox"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Av. 5&#170; SO 3005"
mobile = "+593 099 563 2739"
email = "ventas@bisstox.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Categorías del blog"
posts_title = "Destacado"
featured_post_title = "Publicaciones Destacadas"
recent_post_title = "Publicaciones Recientes"
featured_post_button = "Destacado"
recent_post_button = "Reciente"
read_more_button = "Leer más"
previous_button = "Anterior"
next_button = "Siguiente"
related_posts = "Publicaciones Relacionadas"
showing_posts = "Mostrando Publicaciones de"
no_categories_found = "No se encontraron categorías"
no_tags_found = "No se encontraron etiquetas"

mainSections = ["blog"]
# about widget content
about_widget_content = "Nuestra misión es **ayudar a las empresas a ser mejores en lo que hacen**."
# footer content
footer_content = "Cada empresa, cada negocio alrededor del mundo, puede transformar sus posibilidades a través de la tecnología."
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "Inorizonti"

# 404
error_404_text = "404 No encontrado!"
error_404_button = "Regresar al inicio"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Tecnología que ayuda"
title_small = "a los negocios a ser mejores en lo que hacen"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Potenciamos tu negocio a través de innovadoras soluciones tecnológicas."
button_label = "¡Conócenos!"
button_link = "acerca/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = ""

# cookies
[cookies]
enable = true
expire_days = 2
content = "Este sitio usa cookies. Al continuar usando este sitio, aceptas su uso."
button = "Acepto"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
newsletter_title = "Suscríbete"
newsletter_invitation = "Suscríbete a nuestra lista de email."
newsletter_placeholder = "Escribe tu email"
newsletter_reminder_a = "Al suscribirte aceptas nuestra"
newsletter_reminder_b = "Política de Privacidad"
newsletter_button = "Suscríbeme"
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
